### ISSUE TITLE
코틀린공부하려고 책을 보고있습니다만 문제가있어 연락드렸습니다 여기다 쓴게 맞을까요?

### ISSUE THREAD

**Issue by kim-kwanghoon** [JJJoonngg/ShoppingMallAppExample#1]
챕터 2부분을 따라하고있는데
막히는부분이많아서요

44p - 인텔리제이를 처음 설치해봤는데 이미지에 있는 그래돌 부분 코틀린/JVM 부분을 선택할수가 없네요
         버전은ideaIC-2019.1.4.exe입니다
49p - allOpen{ annot...} 이코드가 그래돌 밑줄이가요
53p - fun main 부분의 실행버튼이 활성화가 되지않습니다

구글을 통해 다양한 시도중인데 잘 안풀려서요 
인텔리제이의 버전을 알 수있을까요?

**Comment by JJJoonngg** [comment]
제가 현재 해당 작업을 진행했던 기기를 만질 시간이 금요일 퇴근하고 나서인데 한번 확인해서 보내드리도록 하겠습니다

**Comment by kim-kwanghoon** [comment]
답기다릴꼐요! ㅎ

**Comment by JJJoonngg** [comment]
해당 책을 제가 현재 찾아보니 가지고 있지 않더군요 

이것이 제 인텔리 버전 현재 셋팅입니다

책 부분에서 오류가 생기시면 따로 구글링을 해보시는걸 추천 드립니다
