### ISSUE TITLE
질문 하나만 더 올리겠습니

### ISSUE THREAD

**Issue by kim-kwanghoon** [JJJoonngg/ShoppingMallAppExample#3]
![image](https://user-images.githubusercontent.com/69333866/99181164-0ba33d80-2770-11eb-9113-d5bbfc960a07.png)

위 그림의 문제가 안풀려서 

답답한 마음에
JJJoonngg /ShoppingMallAppExample 깃에서  
아래 2가지 파일을 받아서 실행해봤지만 문제가 해결이 안되서요 피드백부탁드려요 ㅜㅜ  
ShoppingMallAppExample/ParayoServer/build.gradle   
ShoppingMallAppExample/ParayoServer/src/main/kotlin/com/example/parayo/ParayoApplication.kt  
  
아 그리고 깃말고다른곳에 질문이나 이런글을 올릴 수 있는지 궁금합니다

**Comment by JJJoonngg** [comment]
깃헙말고 다른 분이 다른 곳에서 하고 계시다면 질문은 가능할 것 같습니다
제 코드는 참고용으로 보셔야하고 제가 책의 저자가 아니기 때문에 확답은 못 드리겠습니다

제가 해당 코드를 작업하면서 책과 동일하게 진행한 부분도 있고 그냥 임의로 진행한 코드도 있을겁니다
해당 오류를 구글링 하시면 좀 더 좋은 답변을 얻을 수 있지 않을까 합니다~!
