### ISSUE TITLE
질문하나 요청합니다. findByEmail 메소드 관련하여

### ISSUE THREAD

**Issue by sxi8022** [JJJoonngg/ShoppingMallAppExample#4]
질문하나 요청합니다. findByEmail 메소드 관련하여 질문드립니다. 

![image](https://user-images.githubusercontent.com/42510512/127139162-cc897ba4-b44c-4ea6-8e0c-85c2161882f3.png)

rivate fun checkDuplicates(email: String): Nothing? =
        userRepository.findByEmail(email)?.let {
            throw MailYoException("이미 사용 중인 이메일입니다.")
        }

예제에서 이부분이 에러가 납니다. 

gradle 부분을 확인해도 계속  findByEmail 이걸 수행하려고할때 Invoked Exception 이 뜹니다. 

-- gradle 부분
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.4.32'
    id 'org.springframework.boot' version "2.5.3"
    id "org.jetbrains.kotlin.plugin.spring" version "1.4.32"
    id 'org.jetbrains.kotlin.plugin.jpa' version '1.4.32'
}

apply plugin: 'io.spring.dependency-management'

allOpen {
    annotation("javax.persistence.Entity")
}

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "org.jetbrains.kotlin:kotlin-reflect"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-jdbc"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation 'org.mindrot:jbcrypt:0.4'
    runtimeOnly 'mysql:mysql-connector-java'
}
compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

**Comment by JJJoonngg** [comment]
아마 anko에러인거 같은데
https://stackoverflow.com/questions/52081383/kotlin-backend-internal-error-exception-during-code-generation
관련해서 한번 찾아보시길 바랍니다~!

**Comment by sxi8022** [comment]
> 아마 anko에러인거 같은데
> https://stackoverflow.com/questions/52081383/kotlin-backend-internal-error-exception-during-code-generation
> 관련해서 한번 찾아보시길 바랍니다~!


anko 는 안드로이드 스튜디오에서 설정했고 
제가 뜨는 에러는 인텔리j 에서 뜨는 오류 입니다. 
anko 버전도 0.10.8 이며 

교재  122page 까지 진행했을때 뜨는 에러입니다 ㅠ

**Comment by sxi8022** [comment]
![image](https://user-images.githubusercontent.com/42510512/127272705-b32d5347-1f6f-4c66-8a73-229d7089090d.png)

**Comment by sxi8022** [comment]
> 아마 anko에러인거 같은데
> https://stackoverflow.com/questions/52081383/kotlin-backend-internal-error-exception-during-code-generation
> 관련해서 한번 찾아보시길 바랍니다~!

일단 오류를 어떻게든 해결하긴 했는데 
얼떨떨한 기분이네요 
교재에 hibernate 를 설정한부분을 변경했습니다
 hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        show-sql: true

그리고  나니까 또다른 오류가 뜨는데 
createdAt 이라는 컬럼이 db 에 없다는 메시지가 떠서 
db에 컬럼을 넣고 

User.kt 파일에 들어가서 
@Column(name="create_date")
@Column(name="update_date")

컬럼을 추가했습니다. 책이 초보자를위해 db에 테이블 넣는거하고 
column 어노테이션 설정하는 디테일까지 챙겼으면 좋았을텐데 아쉬운 면이 있네요 감사합니다

**Comment by JJJoonngg** [comment]
저도 읽은지 좀 된책이여서 기억은 안나네요 ㅎㅎ
anko 는 이제 더 이상 사용되지 않는 라이브러리라서 새로운 라이브러리 적용하시는 걸 추천드립니다 ㅎㅎ
